#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# copy dkim samples if none exists
if [[ ! -f "/config/dkim/dkim.key" ]]; then
    cp /defaults/dkim/dkim.key /config/dkim/dkim.key
fi

if [[ ! -f "/config/dkim/dkim.txt" ]]; then
    cp /defaults/dkim/dkim.txt  /config/dkim/dkim.txt
fi