#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:postdrop \
        /config/lib/postfix \
        /config/postfix \
        /config/spool/mail

    lsiown -R abc:abc \
        /config/dkim \
        /run/opendkim
fi

if [[ -f "/config/dkim/default.private" ]]; then
    chmod 600 /config/dkim/default.private
fi